### ISSUE TITLE
Including project as a submodule

### ISSUE THREAD

**Issue by tofutim** [material-components/material-components-flutter-adaptive#40]
I have a couple things I wanted to contribute as PRs and typically include projects as submodules, then use path, e.g., 
```
  adaptive_navigation:
    path: ./material-components-flutter-adaptive/adaptive_navigation
  adaptive_breakpoints: 
    path: ./material-components-flutter-adaptive/adaptive_breakpoints
  adaptive_components: 
    path: ./material-components-flutter-adaptive/adaptive_components
```
When I tried to do this however, I got the following message:

> Because every version of adaptive_components depends on adaptive_navigation from hosted and nihao depends on adaptive_navigation from path, adaptive_components is forbidden.
> So, because nihao depends on adaptive_components any, version solving failed.
> pub get failed (1; So, because nihao depends on adaptive_components any, version solving failed.)
